FROM php:8.3-apache

# ACTUALIZAR EL SISTEMA E INSTALAR DEPENDENCIAS
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        unzip \
        libicu-dev \
        tzdata \
        npm \
        libssl-dev \
        pkg-config \
    && rm -rf /var/lib/apt/lists/*

# CONFIGURAR ZONA HORARIA
ENV TZ=America/Mexico_City

# CONFIGURAR PHP
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# MODIFICAR EL DOCUMENT ROOT DE APACHE
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' \
    /etc/apache2/sites-available/*.conf

RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' \
    /etc/apache2/apache2.conf \
    /etc/apache2/conf-available/*.conf

# INSTALAR EXTENSIONES PHP
RUN docker-php-ext-configure intl \
    && docker-php-ext-install intl mysqli

# INSTALAR COMPOSER
WORKDIR /var/www/html

RUN curl -sS https://getcomposer.org/installer \
    | php -- --install-dir=/usr/local/bin --filename=composer

# INSTALAR SASS
RUN npm install -g sass

# CONFIGURAR APACHE
RUN a2enmod rewrite

# OCULTAR VERSION DE PHP
RUN echo "expose_php=Off" > /usr/local/etc/php/conf.d/security.ini

# INSTALAR Y HABILITAR MONGODB
RUN pecl install mongodb \
    && docker-php-ext-enable mongodb

# CONFIGURAR ARCHIVO DE INICIO
RUN mkdir -p /utils/scripts

COPY ./ms-start.sh /utils/scripts/ms-start.sh

RUN chmod a+x /utils/scripts/ms-start.sh

WORKDIR /var/www/html

ENTRYPOINT ["bash", "/utils/scripts/ms-start.sh"]