FROM python:3.14-slim

# Carpeta de trabajo dentro del contenedor
WORKDIR /root/python/

# Actualizar pip
RUN pip install --upgrade pip

# Instalar dependencias Python
COPY ./python/requirements.txt requirements.txt

RUN pip install -r requirements.txt

# Configuración zona horaria y cron
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    tzdata \
    cron \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=America/Mexico_City

# Configurar crontab
COPY ./python/cronjob /etc/cron.d/cronjob

RUN chmod 0644 /etc/cron.d/cronjob \
    && crontab /etc/cron.d/cronjob

# Configurar archivo de inicio
RUN mkdir -p /utils/scripts

COPY ./ms-start-python.sh /utils/scripts/ms-start.sh

RUN chmod a+x /utils/scripts/ms-start.sh

ENTRYPOINT ["bash", "/utils/scripts/ms-start.sh"]